// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BiometricAccessServiceType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<BiometricAccessOperation> BiometricAccessOperations { get; set; } = new List<BiometricAccessOperation>();
}