// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BiometricAccessOperation
{
    public long Id { get; set; }

    public int? PartnerId { get; set; }

    public Guid? ExternalId { get; set; }

    public string Pin { get; set; }

    public string DocumentNumber { get; set; }

    public string Uid { get; set; }

    public int? ServiceType { get; set; }

    public int? VendorId { get; set; }

    public DateTime? AddedDate { get; set; }

    public double? Similarity { get; set; }

    public string ErrorMessage { get; set; }

    public int? ErrorCode { get; set; }

    public bool? IsSuccessfulOperation { get; set; }

    public string IdempotencyKey { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Patronymic { get; set; }

    public DateTime? BirthDate { get; set; }

    public string BirthAddress { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public DateTime? ExpDate { get; set; }

    public string DocumentType { get; set; }

    public string IssuingCountry { get; set; }

    public string AuthScheme { get; set; }

    public string LiveImage { get; set; }

    public string Nationality { get; set; }

    public string Organization { get; set; }

    public string FaceDetectionReason { get; set; }

    public int? ResponseErrorCode { get; set; }

    public int? BiometricProfileId { get; set; }

    public double? LivenessScore { get; set; }

    public bool? LivenessStatus { get; set; }

    public bool? SimilarityStatus { get; set; }

    public bool? IsVendorServiceUsed { get; set; }

    public string IpAddress { get; set; }

    public string DeviceInfo { get; set; }

    public DateTime? EventDate { get; set; }

    public virtual BiometricProfile BiometricProfile { get; set; }

    public virtual ICollection<KycOperation> KycOperations { get; set; } = new List<KycOperation>();

    public virtual ICollection<ManualAccess> ManualAccesses { get; set; } = new List<ManualAccess>();

    public virtual Partner Partner { get; set; }

    public virtual BiometricAccessServiceType ServiceTypeNavigation { get; set; }

    public virtual Vendor Vendor { get; set; }
}