// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BiometricProfileHistory
{
    public int Id { get; set; }

    public int? BiometricProfileId { get; set; }

    public bool? IsActive { get; set; }

    public int? DocumentTypeId { get; set; }

    public string IamasImage { get; set; }

    public DateTime? AddedDate { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Citizenship { get; set; }

    public string DocumentNumber { get; set; }

    public DateTime? EventDate { get; set; }

    public DateTime? ExpDate { get; set; }

    public string Organization { get; set; }

    public string Address { get; set; }

    public string Patronymic { get; set; }

    public DateTime? BirthDate { get; set; }

    public string BirthAddress { get; set; }

    public string Gender { get; set; }

    public string IssuingCountry { get; set; }

    public string MigrationDocumentType { get; set; }

    public virtual BiometricProfile BiometricProfile { get; set; }

    public virtual DocumentType DocumentType { get; set; }
}