// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BiometricProfile
{
    public int Id { get; set; }

    public string Pin { get; set; }

    public DateTime? AddedDate { get; set; }

    public bool? IsBlocked { get; set; }

    public virtual ICollection<BiometricAccessOperation> BiometricAccessOperations { get; set; } = new List<BiometricAccessOperation>();

    public virtual ICollection<BiometricProfileHistory> BiometricProfileHistories { get; set; } = new List<BiometricProfileHistory>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<KycOperation> KycOperations { get; set; } = new List<KycOperation>();
}