// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Customer
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Patronymic { get; set; }

    public string Pin { get; set; }

    public string DocumentNumber { get; set; }

    public string Uid { get; set; }

    public DateTime? Birth { get; set; }

    public int? PartnerId { get; set; }

    public DateTime? AddedDate { get; set; }

    public int? VendorId { get; set; }

    public string FaceId { get; set; }

    public string BirthAddress { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string LivePhoto { get; set; }

    public int? BiometricProfileId { get; set; }

    public virtual BiometricProfile BiometricProfile { get; set; }

    public virtual Partner Partner { get; set; }

    public virtual Vendor Vendor { get; set; }
}