// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class DefaultVerifier
{
    public int Id { get; set; }

    public string Key { get; set; }

    public double Threshold { get; set; }

    public string ExternalId { get; set; }

    public bool? Main { get; set; }
}