// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Handler
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public int PartnerId { get; set; }

    public string VlhandlerId { get; set; }

    public byte IsCurrent { get; set; }

    public double? LivenessThreshold { get; set; }
}