// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class IdentificationLog
{
    public int Id { get; set; }

    public int PartnerId { get; set; }

    public string Pin { get; set; }

    public DateTime ProcessDate { get; set; }

    public bool IsSuccess { get; set; }

    public double? Similarity { get; set; }

    public string ErrorMessage { get; set; }

    public int? ErrorCode { get; set; }
}