// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class KycSdkOperation
{
    public int Id { get; set; }

    public DateTime Started { get; set; }

    public long? KycOperationId { get; set; }

    public string IamasImage { get; set; }

    public string FirstImage { get; set; }

    public string SecondImage { get; set; }

    public decimal? FirstVerificationLivenessScore { get; set; }

    public decimal? FirstVerificationSimilarityScore { get; set; }

    public decimal? SecondVerificationLivenessScore { get; set; }

    public decimal? SecondVerificationSimilarityScore { get; set; }

    public int? Status { get; set; }

    public byte[] FirstImageChecksum { get; set; }

    public byte[] SecondImageChecksum { get; set; }

    public string FirstImageS3 { get; set; }

    public string SecondImageS3 { get; set; }

    public string IamasImageS3 { get; set; }

    public string SessionId { get; set; }
}