// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class KycServiceType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<KycOperation> KycOperations { get; set; } = new List<KycOperation>();

    public virtual ICollection<PartnerKycServiceType> PartnerKycServiceTypes { get; set; } = new List<PartnerKycServiceType>();
}