// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class ManualAccess
{
    public int Id { get; set; }

    public string Pin { get; set; }

    public string Image { get; set; }

    public int PartnerId { get; set; }

    public int SolutionTypeId { get; set; }

    public DateTime? AddedDate { get; set; }

    public long? KycOperationId { get; set; }

    public long? BiometricAccessOperationId { get; set; }

    public virtual BiometricAccessOperation BiometricAccessOperation { get; set; }

    public virtual KycOperation KycOperation { get; set; }

    public virtual Partner Partner { get; set; }

    public virtual SolutionType SolutionType { get; set; }
}