// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class PartnersVendorsSolution
{
    public int Id { get; set; }

    public int PartnerId { get; set; }

    public int VendorId { get; set; }

    public int SolutionTypeId { get; set; }

    public virtual Partner Partner { get; set; }

    public virtual SolutionType SolutionType { get; set; }

    public virtual Vendor Vendor { get; set; }
}