// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Partner
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte Status { get; set; }

    public string MasterKey { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ParentId { get; set; }

    public string IdempotencyKey { get; set; }

    public bool? AuthRequired { get; set; }

    public bool? DocumentImageVisibility { get; set; }

    public string Tin { get; set; }

    public bool? DocumentDataVisibility { get; set; }

    public bool? PinOnlyServiceAccess { get; set; }

    public int? TrialRequestLimit { get; set; }

    public bool? SdkPartner { get; set; }

    public virtual ICollection<BiometricAccessOperation> BiometricAccessOperations { get; set; } = new List<BiometricAccessOperation>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<KycOperation> KycOperations { get; set; } = new List<KycOperation>();

    public virtual ICollection<ManualAccess> ManualAccesses { get; set; } = new List<ManualAccess>();

    public virtual ParentPartner Parent { get; set; }

    public virtual ICollection<PartnerKycServiceType> PartnerKycServiceTypes { get; set; } = new List<PartnerKycServiceType>();

    public virtual ICollection<PartnersVendorsSolution> PartnersVendorsSolutions { get; set; } = new List<PartnersVendorsSolution>();

    public virtual ICollection<UniversalBiometricOperation> UniversalBiometricOperations { get; set; } = new List<UniversalBiometricOperation>();

    public virtual ICollection<UniversalBiometricProfile> UniversalBiometricProfiles { get; set; } = new List<UniversalBiometricProfile>();

    public virtual ICollection<UniversalBiometricServiceTypePartner> UniversalBiometricServiceTypePartners { get; set; } = new List<UniversalBiometricServiceTypePartner>();

    public virtual ICollection<Verifier> Verifiers { get; set; } = new List<Verifier>();

    public virtual ICollection<Vlrule> Vlrules { get; set; } = new List<Vlrule>();
}