// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class PartnerBiometricAccessServiceType
{
    public int Id { get; set; }

    public int PartnerId { get; set; }

    public int? BiometricAccessServiceTypeId { get; set; }

    public virtual BiometricAccessServiceType BiometricAccessServiceType { get; set; }

    public virtual Partner Partner { get; set; }
}