// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class PartnerKycServiceType
{
    public int Id { get; set; }

    public int PartnerId { get; set; }

    public int KycServiceTypeId { get; set; }

    public virtual KycServiceType KycServiceType { get; set; }

    public virtual Partner Partner { get; set; }
}