// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Sdksession
{
    public int Id { get; set; }

    public string PartnerTransactionId { get; set; }

    public string SessionKey { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Pin { get; set; }

    public string DocumentNumber { get; set; }

    public string Image { get; set; }

    public string Jti { get; set; }

    public int? Status { get; set; }

    public string PublicKey { get; set; }

    public string PrivateKey { get; set; }

    public string EncryptionKey { get; set; }

    public DateTime? Started { get; set; }
}