// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Sdkuser
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public byte? PartnerId { get; set; }

    public string CallbackUrl { get; set; }
}