// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class SimaDataLog
{
    public int Id { get; set; }

    public int ServiceType { get; set; }

    public string CustomerKey { get; set; }

    public string Pin { get; set; }

    public string Uid { get; set; }

    public DateTime Date { get; set; }

    public bool IsSuccess { get; set; }

    public bool? SuccessVerification { get; set; }

    public double? LivenessScore { get; set; }

    public double? Similarity { get; set; }

    public bool? SimilarityStatus { get; set; }

    public string ErrorMessage { get; set; }

    public int? ErrorCode { get; set; }
}