// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class SimaData
{
    public int Id { get; set; }

    public string CustomerName { get; set; }

    public string CustomerKey { get; set; }

    public int? Success { get; set; }

    public int? Total { get; set; }

    public int? PartnerId { get; set; }
}