// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class SolutionType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ManualAccess> ManualAccesses { get; set; } = new List<ManualAccess>();

    public virtual ICollection<PartnersVendorsSolution> PartnersVendorsSolutions { get; set; } = new List<PartnersVendorsSolution>();
}