// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Translation
{
    public int Id { get; set; }

    public string TranslationKey { get; set; }

    public string DefaultDescription { get; set; }

    public string DescAze { get; set; }

    public string DescEng { get; set; }

    public string DescRus { get; set; }

    public DateTime AddedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AddedBy { get; set; }

    public string UpdatedBy { get; set; }
}