// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class UniversalBiometricOperation
{
    public long Id { get; set; }

    public int? PartnerId { get; set; }

    public int? VendorId { get; set; }

    public int? DocumentTypeId { get; set; }

    public bool? IsSuccessfulOperation { get; set; }

    public int? MatchedCandidatesCount { get; set; }

    public double? SimilarityScore { get; set; }

    public bool? SimilarityStatus { get; set; }

    public int? ErrorCode { get; set; }

    public string ErrorMessage { get; set; }

    public string IpAddress { get; set; }

    public string DeviceInfo { get; set; }

    public string MainPhoto { get; set; }

    public string LivePhoto { get; set; }

    public string IdempotencyKey { get; set; }

    public string AuthScheme { get; set; }

    public string PersonId { get; set; }

    public string Pin { get; set; }

    public string DocumentNumber { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Patronymic { get; set; }

    public string Gender { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Address { get; set; }

    public string BirthAddress { get; set; }

    public DateTime? EventDate { get; set; }

    public DateTime? ExpDate { get; set; }

    public string Nationality { get; set; }

    public string Organization { get; set; }

    public string IssuingCountry { get; set; }

    public string MigrationDocumentType { get; set; }

    public DateTime? AddedDate { get; set; }

    public int? ServiceTypeId { get; set; }

    public double? LivenessScore { get; set; }

    public bool? LivenessStatus { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual Partner Partner { get; set; }

    public virtual UniversalBiometricServiceType ServiceType { get; set; }

    public virtual ICollection<UniversalBiometricOperationToProfile> UniversalBiometricOperationToProfiles { get; set; } = new List<UniversalBiometricOperationToProfile>();

    public virtual Vendor Vendor { get; set; }
}